### ISSUE TITLE
Generated ButterKnife.inject() in Fragment isn't working

### ISSUE THREAD

**Issue by cermakcz** [inmite/android-butterknife-zelezny#28]
// I want
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
      return inflater.inflate(R.layout.fragment_profile_detail, container, false);
    }
 
    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
      ButterKnife.inject(this, view);
    }
 
    // I get
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
      ButterKnife.inject(this, inflater.inflate(R.layout.fragment_profile_detail, container, false));
      return inflater.inflate(R.layout.fragment_profile_detail, container, false);
    }

What I get isn't working, because ButterKnife searches for views in a different inflated View (the one inside the ButterKnife.inject() call), than the one I return from the onCreateView() method.

**Comment by destil** [comment]
Fixed today, it will now generate a correct injection in onCreateView method, just like in ButterKnife documentation.

Thanks @LArchaon for a push in Riga :)
