### ISSUE TITLE
Improvement : remove common section of an ID

### ISSUE THREAD

**Issue by Trikke** [inmite/android-butterknife-zelezny#31]
Hi,

first of all, thanks for making our developer lives easier. But i got one small request for an improvement, if you'd think it's possible/handy.

I usually create resource id's for views based on the viewgroup or item they are in. If i make a fragment xml named `fragment_profile`, then all my views/layouts inside that xml will be called `fragment_profile_some_way_to_indentify_view`. A view that shows the name of a user in that xml would be called `fragment_profile_user_name_title`. I do this because on large projects you can run into collisions if there would be several fragments that include a textview to show a user's name.

When then generating the code with your plugin, all my views will be called `mFragmentProfileUserName` and so on. So the question is if you could detect if there is a common string across all the id's you find and remove that in the variable name section. There could even be a tick next to 'create viewholder', to toggle this behaviour. ( 'full variable name' or something )

I'd like to hear your thoughts on this.

**Comment by destil** [comment]
Hi, I think this naming convention is not very helpful. It doesn't matter if multiple fragments have TextView with id "name". You can have same IDs inside one project, collisions are possible only inside one layout. So we don't think this would benefit many people.
Our naming convention to views in Avast is simple "v" - id "name" would generate TextView vName
