### ISSUE TITLE
Request:  Generate ViewInjections for Views

### ISSUE THREAD

**Issue by RealAndyLawton** [inmite/android-butterknife-zelezny#33]
It would be great if you could generate ViewInjections for View subclasses.  We don't use Fragments and have way more Views than Activities.

I realize that there isn't a setContentView concept in a View class, but perhaps you could choose the corresponding layout resource via a dialog.

Thanks!

**Comment by destil** [comment]
Hi, I just tested the plugin on a simple compound view:

    public class CustomView extends LinearLayout {
        public CustomView(Context context) {
            super(context);
            LayoutInflater.from(context).inflate(R.layout.custom_view, this);
        }
    }

When I click to R.layout.custom_view and select Generate, I can generate injections into CustomView class.

**Comment by RealAndyLawton** [comment]
It does work!  Thanks.
