### ISSUE TITLE
How to change the defalut created variable name?

### ISSUE THREAD

**Issue by angelen10** [inmite/android-butterknife-zelezny#34]
How to change the defalut created variable name?For example, I have a TextView in my layout(e.g.activity_main.xml), and it's id is tvName, how to change the default created variable name?What I want is also 'tvName', not 'mTvName'. And then generate an Android Studio Tools?

**Comment by PatrickDattilio** [comment]
In the plugin settings there is an option to set the prefix.

**Comment by destil** [comment]
Go to IDEA Preferences -> ButterKnifeZelezny. I just tested it, it works.
