### ISSUE TITLE
can't find butterknife in generate

### ISSUE THREAD

**Issue by lijianyu** [inmite/android-butterknife-zelezny#35]
![image](https://cloud.githubusercontent.com/assets/5039301/5871942/fb902adc-a31f-11e4-97b8-636319a11172.png)
![image](https://cloud.githubusercontent.com/assets/5039301/5871950/180e4d38-a320-11e4-8ed9-2fbe7e728fa9.png)

android studio 1.0

**Comment by maguireman** [comment]
I'm having the same issue.

**Comment by lijianyu** [comment]
I have already solved，the current application will add butterknife package,i before add in my library.
