### ISSUE TITLE
Ids on <include/> tagged layouts are ignored

### ISSUE THREAD

**Issue by RomainPiel** [inmite/android-butterknife-zelezny#8]
if I have include tags in my layout, they are ignored:
```xml
<include
      android:id="@+id/my_id"
      layout="@layout/my_layout"/>
```

**Comment by boylenssen** [comment]
What you probably could do, is:

@injectView(R.id.my_id)
View myId;

// some class you created with the ID's and add the @injectView in there for the fields
MyIDViews myIdViews;

Butterknife.inject(this);
Butterknife.inject(myIdViews, myId);

Haven't tried it though

**Comment by destil** [comment]
I have tested this today, ids in <include> layout are not ignored, but injected into the class. I don't think it's beneficial to create an artificial View for those views in the inclusion like @r-gurzkowski's commit suggests.
